set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(SECCAM_HOST_TOOLS_ROOT "$ENV{SECCAM_HOST_TOOLS_ROOT}" CACHE PATH "Milk-V host-tools root")

if(NOT SECCAM_HOST_TOOLS_ROOT)
  set(SECCAM_HOST_TOOLS_ROOT "${CMAKE_CURRENT_LIST_DIR}/../host_tools/toolchain")
endif()

set(SECCAM_TOOLCHAIN_PREFIX "${SECCAM_HOST_TOOLS_ROOT}/gcc/riscv64-linux-musl-x86_64/bin/riscv64-unknown-linux-musl-")
set(SECCAM_C_COMPILER "${SECCAM_TOOLCHAIN_PREFIX}gcc")
set(SECCAM_CXX_COMPILER "${SECCAM_TOOLCHAIN_PREFIX}g++")

if(NOT EXISTS "${SECCAM_C_COMPILER}")
  message(FATAL_ERROR "Missing RISC-V musl compiler: ${SECCAM_C_COMPILER}. Run scripts/prepare_duo256m_sdk.sh first.")
endif()

set(CMAKE_C_COMPILER "${SECCAM_C_COMPILER}")
set(CMAKE_CXX_COMPILER "${SECCAM_CXX_COMPILER}")
set(CMAKE_AR "${SECCAM_TOOLCHAIN_PREFIX}ar")
set(CMAKE_RANLIB "${SECCAM_TOOLCHAIN_PREFIX}ranlib")
set(CMAKE_STRIP "${SECCAM_TOOLCHAIN_PREFIX}strip")

set(CMAKE_C_FLAGS_INIT "-mcpu=c906fdv -march=rv64imafdcv0p7xthead -mcmodel=medany -mabi=lp64d")
set(CMAKE_EXE_LINKER_FLAGS_INIT "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
